[tool.pytest.ini_options]
minversion = "7.4"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = """
    -v
    --strict-markers
    --tb=short
    --disable-warnings
"""
markers = [
    "integration: Integration tests",
    "security: Security-related tests",
    "e2e: End-to-end tests",
    "slow: Tests that take a long time to run",
]
