"""Add menu_change_logs table for audit logging

Revision ID: 2f4aeea60b82
Revises: cc07ab120b94
Create Date: 2025-10-19 00:56:32.163833

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f4aeea60b82"
down_revision: Union[str, None] = "cc07ab120b94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create menu_change_logs table
    op.create_table(
        "menu_change_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("changes", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["menu_id"], ["menus.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_menu_change_logs_id"), "menu_change_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_change_logs_menu_id"),
        "menu_change_logs",
        ["menu_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_menu_change_logs_store_id"),
        "menu_change_logs",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_menu_change_logs_user_id"),
        "menu_change_logs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_menu_change_logs_action"), "menu_change_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_menu_change_logs_changed_at"),
        "menu_change_logs",
        ["changed_at"],
        unique=False,
    )

    op.alter_column(
        "menu_categories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "menu_categories",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "menu_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "menu_categories",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_menu_categories_display_order", table_name="menu_categories")
    op.create_index(
        op.f("ix_menu_categories_id"), "menu_categories", ["id"], unique=False
    )
    op.drop_index("ix_orders_store_ordered", table_name="orders")
    op.drop_index("ix_orders_store_ordered_status", table_name="orders")
    op.drop_index("ix_orders_store_status", table_name="orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_orders_store_status", "orders", ["store_id", "status"], unique=False
    )
    op.create_index(
        "ix_orders_store_ordered_status",
        "orders",
        ["store_id", "ordered_at", "status"],
        unique=False,
    )
    op.create_index(
        "ix_orders_store_ordered", "orders", ["store_id", "ordered_at"], unique=False
    )
    op.drop_index(op.f("ix_menu_categories_id"), table_name="menu_categories")
    op.create_index(
        "ix_menu_categories_display_order",
        "menu_categories",
        ["display_order"],
        unique=False,
    )
    op.alter_column(
        "menu_categories",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "menu_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "menu_categories",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "menu_categories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )

    # Drop menu_change_logs table
    op.drop_index(op.f("ix_menu_change_logs_changed_at"), table_name="menu_change_logs")
    op.drop_index(op.f("ix_menu_change_logs_action"), table_name="menu_change_logs")
    op.drop_index(op.f("ix_menu_change_logs_user_id"), table_name="menu_change_logs")
    op.drop_index(op.f("ix_menu_change_logs_store_id"), table_name="menu_change_logs")
    op.drop_index(op.f("ix_menu_change_logs_menu_id"), table_name="menu_change_logs")
    op.drop_index(op.f("ix_menu_change_logs_id"), table_name="menu_change_logs")
    op.drop_table("menu_change_logs")
    # ### end Alembic commands ###
