"""add_guest_sessions_and_cart

Revision ID: 8b8905e3b726
Revises: 2f4aeea60b82
Create Date: 2025-10-19 09:59:35.364083

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b8905e3b726"
down_revision: Union[str, None] = "2f4aeea60b82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 制約が存在する場合のみ削除（マージブランチ対応）
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    fk_constraints = inspector.get_foreign_keys("guest_cart_items")
    constraint_names = [fk["name"] for fk in fk_constraints]
    
    if "guest_cart_items_session_id_fkey" in constraint_names:
        op.drop_constraint(
            "guest_cart_items_session_id_fkey", "guest_cart_items", type_="foreignkey"
        )
    
    op.create_foreign_key(
        None,
        "guest_cart_items",
        "guest_sessions",
        ["session_id"],
        ["session_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "menu_categories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "menu_categories",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "menu_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "menu_categories",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    
    # インデックスの存在チェック（マージブランチ対応）
    indexes = inspector.get_indexes("menu_categories")
    index_names = [idx["name"] for idx in indexes]
    
    if "ix_menu_categories_display_order" in index_names:
        op.drop_index("ix_menu_categories_display_order", table_name="menu_categories")
    
    if "ix_menu_categories_id" not in index_names:
        op.create_index(
            op.f("ix_menu_categories_id"), "menu_categories", ["id"], unique=False
        )
    
    # ordersテーブルのインデックス確認
    order_indexes = inspector.get_indexes("orders")
    order_index_names = [idx["name"] for idx in order_indexes]
    
    if "ix_orders_store_ordered" in order_index_names:
        op.drop_index("ix_orders_store_ordered", table_name="orders")
    if "ix_orders_store_ordered_status" in order_index_names:
        op.drop_index("ix_orders_store_ordered_status", table_name="orders")
    if "ix_orders_store_status" in order_index_names:
        op.drop_index("ix_orders_store_status", table_name="orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_orders_store_status", "orders", ["store_id", "status"], unique=False
    )
    op.create_index(
        "ix_orders_store_ordered_status",
        "orders",
        ["store_id", "ordered_at", "status"],
        unique=False,
    )
    op.create_index(
        "ix_orders_store_ordered", "orders", ["store_id", "ordered_at"], unique=False
    )
    op.drop_index(op.f("ix_menu_categories_id"), table_name="menu_categories")
    op.create_index(
        "ix_menu_categories_display_order",
        "menu_categories",
        ["display_order"],
        unique=False,
    )
    op.alter_column(
        "menu_categories",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "menu_categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "menu_categories",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "menu_categories",
        "display_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_constraint(
        "guest_cart_items_session_id_fkey", "guest_cart_items", type_="foreignkey"
    )
    op.create_foreign_key(
        "guest_cart_items_session_id_fkey",
        "guest_cart_items",
        "guest_sessions",
        ["session_id"],
        ["session_id"],
    )
    # ### end Alembic commands ###
